//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookStore.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string ISBN { get; set; }
        public string BookId { get; set; }
        public string Titlte { get; set; }
        public string Descripton { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Publisher { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
